site_name: CodeIgniter Markdown Pages
site_description: Documentation for Markdown Pages library for CodeIgniter 4 framework

theme:
  name: material
  logo: assets/flame.svg
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant

extra:
  homepage: https://michalsn.github.io/codeigniter-markdown-pages

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/michalsn/codeigniter-markdown-pages
      name: GitHub

site_url: https://michalsn.github.io/codeigniter-markdown-pages
repo_url: https://github.com/michalsn/codeigniter-markdown-pages
edit_uri: edit/develop/docs/

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: false

extra_css:
  - assets/github-dark-dimmed.css

extra_javascript:
  - https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.6.0/build/highlight.min.js
  - assets/hljs.js

nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Basic Usage: basic_usage.md
  - Pages: pages.md
  - Search: search.md
  - Classes:
      - Dir: classes/dir.md
      - File: classes/file.md
      - Content: classes/content.md
      - Results: classes/results.md
      - Result: classes/result.md
